<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVieL5Gp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVieL5Gp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVieL5Gp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVieL5Gp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVieL5Gp\App_KernelDevDebugContainer([
    'container.build_hash' => 'VieL5Gp',
    'container.build_id' => 'be84ff94',
    'container.build_time' => 1661932041,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVieL5Gp');
