<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDBEJ9HC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDBEJ9HC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDBEJ9HC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDBEJ9HC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDBEJ9HC\App_KernelDevDebugContainer([
    'container.build_hash' => 'DBEJ9HC',
    'container.build_id' => '8d9ddb79',
    'container.build_time' => 1661765128,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDBEJ9HC');
